### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by reach2rv** [adamosoftware/AoLicensing#1]
I guess Database is missing or do we need to create our own structure of Database

**Comment by adamosoftware** [comment]
hi there, I'm not quite sure what you're referring to. Do you mean like the CRUD operations in [LicenseManager](https://github.com/adamosoftware/AoLicensing/blob/master/AoLicensing.Server/LicenseManager.cs) for example? You're right I should document the dependency on my ORM project Postulate.Lite. [Nuget](https://www.nuget.org/packages/Postulate.Lite.SqlServer)
